### PR TITLE
update plantuml to 8047

### PR DESCRIPTION
**Pull request by btomala**
I made update version of plantuml, it require few changes in download script because it not compile. I don't understand why you didn't use jar version of palntuml?

### CODE REVIEW

**Comment by adamdecaf** [comment]
@btomala We compile the source from the Apache2 licensed distribution. We prefer that license over the others. The pre-packed `.jar` doesn't seem to have a license file so that was a bit confusing to us. 

I was able to get your branch to build with the following added to the download file. (I also ran it locally.) It seems the jar has `net/sourceforge` and `sourceforge/` directories. 

```
rm -rf src/main/java/sourceforge
```

**Comment by adamdecaf** [comment]
ok to test

**Comment by btomala** [comment]
Yes, you have right jar didn't contain license file. Diff is large because there is a lot of change in the plantuml sources. 

I already prepare another PR with adding settings key to set up extension of rendered file e.x. txt. When your merge this one I will rise another If you don't mind.

**Comment by adamdecaf** [comment]
Sure thing. I double-checked with myself that they're doing some funky C -> java translation: https://github.com/plantuml/smetana/blob/master/graphviz-2.38.0/lib/cdt/dtdisc.c

**Pull request merged**
