### PR TITLE
Added support for all diagram types

### PR DESCRIPTION
**Pull request by rolandtritsch**
Hi All, here are the changes that I made ...

* added a/the dependency on plantuml (removed the need to have/use/download the plantuml source code into the repo)
* refactored/renamed the code to express that all diagram types are supported (not only sequence diagrams)
* added tests for all diagram types and all keys

Let me know, if you will merge this back into your master or if you want me to maintain my own fork.

Regards ...
     Roland

### CODE REVIEW

**Comment by adamdecaf** [comment]
ok to test

**Comment by adamdecaf** [comment]
We haven't revisited if using the jar would be alright, but [it doesn't seem to contain a license](https://github.com/Banno/sbt-plantuml-plugin/pull/5#issuecomment-245045414) so we've opted in the past to be more explicit. (So-as to avoid having this project be GPL'd in our private codebases.)

I'll check this out more on Monday, but it's looking fine to me. Thanks!

**Comment by rolandtritsch** [comment]
Found out that mvnrepository only shows releases up to 8059, but the latest plantuml release is actually on repo1.maven.org. Bumped the version to the latest.

**Comment by adamdecaf** [comment]
@rolandtritsch It doesn't seem that we're able to accept the change to downloading the .jar. In [checking the POM](https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/1.2017.15/plantuml-1.2017.15.pom) (and downloaded `.jar`) the license bundled with is GPL. 

We could look at upgrading plantuml's bundled source in this repo and applying the same changes you made.

**Comment by rolandtritsch** [comment]
Ooohhh ... I see. Have raised an issue to get this fixed (https://github.com/plantuml/plantuml/issues/66).

**Comment by adamdecaf** [comment]
@rolandtritsch Cool, thanks for that! Do you want me to get your changes merged into master (with the updated source files pulled in) or would you be okay running on your fork until the ASL jars are published?

**Comment by rolandtritsch** [comment]
I think it is better to keep it in one place. So yes, if you can, please merge my changes. In parallel I will work with the plantuml guys to get a/the ASL build up on the maven repo.

**Comment by adamdecaf** [comment]
@rolandtritsch Just saw this again (from https://github.com/Banno/sbt-plantuml-plugin/issues/9). We don't use this plugin anymore. Would you be interested in taking it over?

**Pull request closed without merging**
